name = "GroupTools"
uuid = "1a3c8808-2843-4c72-af8e-d50ed15039bf"
authors = ["Olivier Verdier <olivier.verdier@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
